version: '3'
services:
    eorzea:
        image: python:3.9-buster
        container_name: eorzea
        volumes:
            - .:/eorzea
        working_dir: /eorzea
        command: sh .sh/python_init.sh
        stdin_open: true
        tty: true