name: Test

on:
  push:
    branches: [master, dev, ci_test]
    tags-ignore:
      - "**"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Sync time
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install ntpdate
          sudo ntpdate pool.ntp.org

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.8
          poetry install

      - name: Lint code
        run: |
          poetry run flake8

      - name: Run pytest
        run: |
          poetry run pytest
